import React from 'react';
import {
  Upload,
  FileText,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  Download,
  User,
  Mail,
  Phone,
  MapPin,
  Globe,
  Briefcase,
  GraduationCap,
  Award,
  Calendar,
  Clock,
  DollarSign,
  TrendingUp,
  Menu,
  LogOut,
  Settings,
  Home,
  FolderOpen,
  Plus,
  Edit,
  Trash2,
  Search,
  Filter,
  RefreshCw,
  AlertCircle,
  CheckCircle,
  Info,
  Loader2,
  Copy,
  ExternalLink,
  Link,
  Linkedin,
  Github,
  Building,
  Target,
  Zap,
  Shield,
  Star,
  Heart,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Database,
  Cloud,
  CloudUpload,
  CloudDownload,
  Folder,
  File,
  FileCode,
  Code,
  Terminal,
  Cpu,
  Monitor,
  Smartphone,
  Tablet,
  Headphones,
  Camera,
  Image,
  Film,
  Music,
  Volume,
  Mic,
  Video,
  Bookmark,
  Tag,
  Tags,
  Hash,
  AtSign,
  Send,
  Inbox,
  Archive,
  Paperclip,
  BarChart,
  BarChart2,
  PieChart,
  Activity,
  Layers,
  Grid,
  List,
  Package,
  Package2,
  Server,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  ArrowLeft,
  ArrowRight,
  CreditCard,
  Infinity,
  Sparkles
} from 'lucide-react';

export const Icons = {
  upload: Upload,
  fileText: FileText,
  check: Check,
  x: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  download: Download,
  user: User,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  globe: Globe,
  briefcase: Briefcase,
  graduationCap: GraduationCap,
  award: Award,
  calendar: Calendar,
  clock: Clock,
  dollarSign: DollarSign,
  trendingUp: TrendingUp,
  menu: Menu,
  logOut: LogOut,
  settings: Settings,
  home: Home,
  folderOpen: FolderOpen,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  search: Search,
  filter: Filter,
  refresh: RefreshCw,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  info: Info,
  loader: Loader2,
  copy: Copy,
  externalLink: ExternalLink,
  link: Link,
  linkedin: Linkedin,
  github: Github,
  building: Building,
  target: Target,
  zap: Zap,
  shield: Shield,
  star: Star,
  heart: Heart,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  database: Database,
  cloud: Cloud,
  cloudUpload: CloudUpload,
  cloudDownload: CloudDownload,
  folder: Folder,
  file: File,
  fileCode: FileCode,
  code: Code,
  terminal: Terminal,
  cpu: Cpu,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  headphones: Headphones,
  camera: Camera,
  image: Image,
  film: Film,
  music: Music,
  volume: Volume,
  mic: Mic,
  video: Video,
  bookmark: Bookmark,
  tag: Tag,
  tags: Tags,
  hash: Hash,
  at: AtSign,
  send: Send,
  inbox: Inbox,
  archive: Archive,
  paperclip: Paperclip,
  barChart: BarChart,
  barChart2: BarChart2,
  pieChart: PieChart,
  activity: Activity,
  layers: Layers,
  grid: Grid,
  list: List,
  package: Package,
  package2: Package2,
  server: Server,
  wifi: Wifi,
  wifiOff: WifiOff,
  battery: Battery,
  batteryCharging: BatteryCharging,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  creditCard: CreditCard,
  infinity: Infinity,
  sparkles: Sparkles,
  refreshCw: RefreshCw
};

export default Icons;